version: '3.7'

services:
  postgresql:
    container_name: postgres
    image: postgres:15.2-alpine3.17
    env_file:
      - .env
    volumes:
      - /opt/docker/postgres/var/lib/postgresql:/var/lib/postgresql
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - custom

  app:
    build: .
    container_name: app
    depends_on:
      postgresql:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - custom

networks:
  custom:
    driver: bridge
    